/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background: '#0d1512',
        surface: '#0d1512',
        'surface-dim': '#0d1512',
        'surface-container-lowest': '#08100d',
        'surface-container-low': '#161d1a',
        'surface-container': '#19211e',
        'surface-container-high': '#242c28',
        'surface-container-highest': '#2f3633',
        'surface-bright': '#333b37',
        'surface-variant': '#2f3633',
        'on-surface': '#dce4df',
        'on-surface-variant': '#bacac2',
        'on-background': '#dce4df',
        'outline': '#85948d',
        'outline-variant': '#3b4a44',
        primary: '#46f1c5',
        'primary-container': '#00d4aa',
        'primary-fixed': '#55fcd0',
        'primary-fixed-dim': '#28dfb5',
        'on-primary': '#00382b',
        'on-primary-container': '#005643',
        'on-primary-fixed': '#002118',
        'surface-tint': '#28dfb5',
        secondary: '#ffb955',
        'secondary-container': '#dc9100',
        'secondary-fixed': '#ffddb4',
        'secondary-fixed-dim': '#ffb955',
        'on-secondary': '#452b00',
        'on-secondary-container': '#4f3100',
        'on-secondary-fixed': '#291800',
        tertiary: '#ffcea6',
        'tertiary-container': '#ffa858',
        'tertiary-fixed': '#ffdcc1',
        'tertiary-fixed-dim': '#ffb77a',
        'on-tertiary': '#4c2700',
        'on-tertiary-container': '#733e00',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#dce4df',
        'inverse-on-surface': '#2a322f',
        'inverse-primary': '#006b55',
      },
      fontFamily: {
        syne: ['Syne', 'sans-serif'],
        sans: ['DM Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      animation: {
        'spin-slow': 'spin 3s linear infinite',
        'float': 'float 5s ease-in-out infinite',
        'breathe': 'breathe 4s ease-in-out infinite',
        'scan': 'scan 3s linear infinite',
        'blink': 'blink 1s step-end infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        breathe: {
          '0%, 100%': { borderColor: 'rgba(26,39,64,1)' },
          '50%': { borderColor: 'rgba(70,241,197,0.5)', boxShadow: '0 0 16px rgba(70,241,197,0.08) inset' },
        },
        scan: {
          '0%': { top: '-4px', opacity: '1' },
          '90%': { opacity: '1' },
          '100%': { top: '100%', opacity: '0' },
        },
        blink: {
          '50%': { borderColor: 'transparent' },
        },
      },
      boxShadow: {
        'glow-primary': '0 0 20px rgba(70,241,197,0.4)',
        'glow-primary-sm': '0 0 10px rgba(70,241,197,0.25)',
        'glow-secondary': '0 0 20px rgba(255,185,85,0.4)',
      },
    },
  },
  plugins: [],
};
